# Generated by Django 2.2.3 on 2019-07-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20190729_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
